### ISSUE TITLE
Issue with optional actionWhatIfNot argument, return value is lost

### ISSUE THREAD

**Issue by gezeta-id** [thecodrr/WhatIfJS#1]
There seems to be an error with the optional `actionWhatIfNot` argument. It's return value is lost.

An example. This one works as expected:

```javascript
"I am a string builder."
    .trim()
    .whatIf(true, ctx => {
      return ctx.slice(10);
    }, function() { return "omg"; })
    .toUpperCase();
// returns: "ING BUILDER."
```
But, this one doesn't:

```javascript
"I am a string builder."
    .trim()
    .whatIf(false, ctx => {
      return ctx.slice(10);
    }, function() { return "omg"; })
    .toUpperCase();
// throws a TypeError: "I am a string builder.".trim(...).whatIf(...) is undefined
```

The problem is in [index.js line #76](https://github.com/thecodrr/WhatIfJS/blob/d443abc3973ab92ef9ec5fe0f23cb1098d99e1a1/index.js#L76). When the `actionWhatIfNot` is called, its result is not returned back up.

**Comment by thecodrr** [comment]
Hi! Thanks for the first issue! Would love a PR if you have the time : )
